# Generated by Django 2.0.2 on 2018-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='picture_url',
            new_name='image_url',
        ),
    ]
