# Generated by Django 2.0.2 on 2018-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180218_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
