# Generated by Django 2.0.2 on 2018-03-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_grade'),
    ]

    operations = [
        migrations.RenameModel('Store', 'Question')
    ]
