# Generated by Django 2.0.2 on 2018-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20180310_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(choices=[(True, 'Y'), (False, 'N')], default=True),
        ),
    ]
