# Generated by Django 2.0.2 on 2018-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
