# Generated by Django 2.0.2 on 2018-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_showing',
            field=models.BooleanField(default=False),
        ),
    ]
