# Generated by Django 2.0.2 on 2018-03-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_is_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
